name: wecount
description: The social ledger app.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <4.0.0"

dependency_overrides:
  firebase_core_platform_interface: 4.5.1
  
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  provider: ^6.0.3
  image: ^3.2.0
  url_launcher: ^6.1.3
  image_picker: ^0.8.5+3
  sqflite: ^2.0.2+1
  photo_view: ^0.14.0
  auto_size_text: ^3.0.0
  fluttertoast: ^8.0.9
  shared_preferences: ^2.0.15
  local_auth: ^2.1.0
  google_maps_flutter: ^2.1.8
  flutter_google_places: ^0.3.0
  location: ^4.4.0
  geocoding: ^2.0.4
  pie_chart: ^5.3.1
  # month_picker_dialog: ^0.4.0
  fl_chart: ^0.51.0
  flutter_sticky_header: ^0.6.3
  flutter_calendar_carousel: ^2.2.0
  google_sign_in: ^5.3.3
  firebase_core: ^1.24.0
  firebase_analytics: ^9.1.10
  firebase_auth: ^3.3.20
  cloud_firestore: ^3.1.18
  firebase_storage: ^10.2.18
  firebase_messaging: ^13.1.0
  flutter_config: ^2.0.0
  flutter_native_image: ^0.0.6+1
  logger: ^1.1.0
  flutter_spinkit: ^5.1.0
  flutter_hooks: ^0.18.5+1
  freezed_annotation: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.3
  flutter_native_splash: ^2.2.3+1
  mockito: ^5.2.0
  build_runner: ^2.3.2
  freezed: ^2.2.1
  json_serializable: ^6.5.4
  flutter_lints: ^2.0.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "res/icons/AppIcon.png"

flutter_native_splash:
  image: res/icons/wecount.png
  color: "#0DB293"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - res/langs/en.json
    - res/langs/ko.json
    - res/icons/
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.zejpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
